### PR TITLE
Add search

### PR DESCRIPTION
**Pull request by mfelsche**
This adds a very simple search. It requires to have the following in your config.toml:

```
[outputs]
  home = ["HTML", "JSON"]
  page = ["HTML"]
```

(A pony-tutorial PR for that change is here: https://github.com/ponylang/pony-tutorial/pull/360 ).

the search results need to be styled properly and also some peview (maybe with highlighted query terms) should be shown.

If anybody has some good js or css advice, feel free to apply it.

### CODE REVIEW

**Comment by SeanTAllen** [comment]
What's the proper way to test this?

**Comment by mfelsche** [comment]
You can checkout the tutorial PR https://github.com/ponylang/pony-tutorial/pull/360 and point the theme submodule to the `search` branch. This is how i work locally.

And then you call `hugo server` and enjoy.

**Comment by mfelsche** [comment]
@SeanTAllen This is now ready from my side. 

The js code is horrible, but works. CSS is ragged, but results look ok-ish (to me).
I've only tested in firefox and chromium on linux. At least some safari tests would be helpful.

**Comment by SeanTAllen** [comment]
This is looking good to me

**Pull request merged**
